### ISSUE TITLE
[FEAT] 북마크 API 기능 구현

### ISSUE THREAD

**Issue by yony-k** [yony-k/LitLink#13]
## 🔗 Description

북마크 RESTful API 기능을 구현합니다.

## 🔗 To-do

- [x] 북마크 목록 조회 기능 구현
- [x] 북마크 상세 조회 기능 구현
- [x] 북마크 좋아요 기능 구현
- [x] 북마크 공유 기능 구현
- [x] 북마크 삭제 기능 구현

## 🔗 ETC

2024.09.19
