### ISSUE TITLE
[FEAT] 엔티티 생성

### ISSUE THREAD

**Issue by yony-k** [yony-k/LitLink#3]
## 🔗 Description

엔티티를 설정합니다.

## 🔗 To-do

- [x] Member 엔티티 생성
- [x] Book 엔티티 생성
- [x] Note 엔티티 생성

## 🔗 ETC

2024.09.17
